"use strict";
let message1 = "Hello";
message1 = "bye";
console.log(message1);
let age1 = 26;
age1 = 27;
console.log(age1);
let isActive = false;
let numberArray = [1, 2, 3];
let data = "this could be anything";
data = 42;
console.log(data);
